// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApmIr_PDOFvxsl7RcX-CfQLkTer7mttpw',
    appId: '1:498034879730:web:c6158e04bcaa32f61cf46b',
    messagingSenderId: '498034879730',
    projectId: 'notesapp-1705b',
    authDomain: 'notesapp-1705b.firebaseapp.com',
    storageBucket: 'notesapp-1705b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMO2kRt8lQE1XQW1Ulxc4IQmOSVSs7zFQ',
    appId: '1:498034879730:android:6cd4fcec6675f4a11cf46b',
    messagingSenderId: '498034879730',
    projectId: 'notesapp-1705b',
    storageBucket: 'notesapp-1705b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCumgbwVj6aM6xeemsW-1UhauM4W4JAM-s',
    appId: '1:498034879730:ios:566d10f2bf280b6c1cf46b',
    messagingSenderId: '498034879730',
    projectId: 'notesapp-1705b',
    storageBucket: 'notesapp-1705b.appspot.com',
    iosBundleId: 'com.example.fluttertodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCumgbwVj6aM6xeemsW-1UhauM4W4JAM-s',
    appId: '1:498034879730:ios:566d10f2bf280b6c1cf46b',
    messagingSenderId: '498034879730',
    projectId: 'notesapp-1705b',
    storageBucket: 'notesapp-1705b.appspot.com',
    iosBundleId: 'com.example.fluttertodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApmIr_PDOFvxsl7RcX-CfQLkTer7mttpw',
    appId: '1:498034879730:web:7a2cdcbee37cf2a51cf46b',
    messagingSenderId: '498034879730',
    projectId: 'notesapp-1705b',
    authDomain: 'notesapp-1705b.firebaseapp.com',
    storageBucket: 'notesapp-1705b.appspot.com',
  );
}
